services:
    wowapps.slackbot:
        class: WowApps\SlackBundle\Service\SlackBot
        arguments:
            - "%wowapps.slackbot.config%"
            - "@wowapps.slackbot.validator"

    wowapps.slackbot.validator:
        class: WowApps\SlackBundle\Service\SlackMessageValidator
