language: php
sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: SKELETON_VERSION="^3.4"
        - php: 7.1
          env: SKELETON_VERSION="^4.0"

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer create-project "symfony/skeleton:${SKELETON_VERSION}" flex
    - composer config extra.symfony.allow-contrib true

script: ./vendor/bin/phpunit --verbose
